version: '1.0'

services:
  api:
    build:
      context: ./vehicles-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha
    depends_on:
      - postgres
    networks:
      - rafa-net

  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: backend_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rafa-net

volumes:
  postgres_data:

networks:
  rafa-net:
    driver: bridge