server:
  port: 8081
spring:
  application:
    name:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_db
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true




