spring:
  application:
    name: vehicles-api

  # API
  datasource:
    url: jdbc:postgresql://dpg-cuqeqb9opnds73cs3ng0-a.oregon-postgres.render.com:5432/backend_db_drr2
    username: vehicles_user
    password: pfnd1gr2hx4xtji1AAPODkmIjHNWIQ2b
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

---

spring.config.activate.on-profile: dev

# TESTES
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: false

---

# ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, logfile
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      http:
        server:
          requests: true
  web:
    base-path: /actuator
