spring:
  application:
    name: vehicles-api

  # Api
  datasource:
    url: jdbc:postgresql://postgres:5432/backend_db
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

---

spring.config.activate.on-profile: dev

# Testes
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: false

---

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, logfile
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      http:
        server:
          requests: true
  web:
    base-path: /actuator

---